### ISSUE TITLE
Activity not updating

### ISSUE THREAD

**Issue by MonstaAU** [timgreen/opaler#6]
Currently having issues with the activity feed updating for all cards on my account. Keeps showing in app as:
"Oops, something went wrong when connect to opal.com.au, please try again later"

Working: Card Balances
Not working: Activity data sync, trip counter.

Attempted the following steps unsuccessfully:
Reset password
Removed history & attempt resync.
Removed account and re-added.

Have logged into both the full opal site and the mobile site, both working without issue on my account.

Device: HTC One M9, current Telstra Firmware

**Comment by ufohunter** [comment]
I'm getting the same problem.

**Comment by timgreen** [comment]
This is due to the changes on opal.com.au. They added spaces in the "Journey
number" columns. According to the error report, it starts this Monday. I will release a new version now, the update should be available on Play Store later today.

**Comment by MonstaAU** [comment]
Awesome, thanks Tim.

Really hated having to install Opal Mobile to check the trip detail. I did like their report page though, might be useful to incorporate something similar in time.

**Comment by timgreen** [comment]
Fixed it in https://github.com/timgreen/opaler/commit/651ae5aac7f1ff953c91c08ffe71c2d7cd26ea7c . New version available in Beta testing channel now.
